### ISSUE TITLE
Will not run on pinephone

### ISSUE THREAD

**Issue by yara-blue** [dskleingeld/pods#1]
Iced depends on either a Vulkan or OpenGL backend (opengl via glow). The shaders for Iced are written in `GLSL 3.3` and the pinephones old Mali 400 mp2 GPU only supports up to `OpenGL ES 1.0` and `OpenGL 1.2`.

Two possible paths forward:

-  rewrite all shaders used by iced (at least [glow_glyph](https://github.com/hecrj/glow_glyph)) to one of those versions.
-  find a different UI library 

Need to investigate what shaders need to be translated. One way of doing that could be to remove all shader code and lower the version to 1.2 then see if the shaders compile on the _pinephone_.

**Comment by yara-blue** [comment]
This glow-glyph fork has `OpenGL ES 3.0` instead of `OpenGL 3.0` https://github.com/tedsta/glow_glyph/blob/master/src/shader/vertex.vert

**Comment by yara-blue** [comment]
More OpenGL 3.3 [shaders](https://github.com/hecrj/iced/tree/master/glow/src/shader) found

**Comment by yara-blue** [comment]
Iced seems to have a plan for a software rendering option in the [future](https://github.com/hecrj/iced/issues/457#issuecomment-663678669) for now its probably better to see if there is another gui framework and otherwise give up....

**Comment by yara-blue** [comment]
useful comment for transpiling the shaders https://stackoverflow.com/questions/42231698/how-to-convert-glsl-version-330-core-to-glsl-es-version-100

**Comment by black-puppydog** [comment]
This is why I was asking whether you had compiled in on the PP over on HN. :P
But I don't know enough about this (never written GL anything in my life) so I didn't want to say "it doesn't work".

Do you have preferences for a different UI framework?

**Comment by yara-blue** [comment]
I only got a pinephone yesterday, but certainly learned a lesson here :). Its a pitty since I just got streaming audio working the day before.

I had one computer graphics course in OpenGL, so this weekend I am trying to see if I can backport/transpile the shaders to `GLSL ES 1.0`. Starting with `glow_glyph`. I got that compiling and running without panics by disabling a part of the shader and transpiling the rest. The hard part will be to rewrite the disabled part, since it uses a hardware feature not available on `GLSL ES 1.0` 

If that doesn't go anywhere I'll see which frameworks I can get running on the phone. I would prefer something cross platform, if this works out I want to add some kind of syncing feature.

**Comment by black-puppydog** [comment]
BTW in case you hadn't seen this, this is the only issue for iced where mobile is really discussed.
It's not deep discussion. But the dev doesn't seem to be against it, it's just a matter of resources.

(But since in that issue, everyone is talking about android/iOS, it might be worth creating a new issue and clarifying how it differs in  scope/purpose)

**Comment by yara-blue** [comment]
> BTW in case you hadn't seen this, this is the only issue for iced where mobile is really discussed.
> It's not deep discussion. But the dev doesn't seem to be against it, it's just a matter of resources.
> 
> (But since in that issue, everyone is talking about android/iOS, it might be worth creating a new issue and clarifying how it differs in scope/purpose)

I might be missing a link in there? Assuming [this](https://github.com/hecrj/iced/issues/302) issue, the only thing I really fear is scrolling. I know buttons will work since touch presses should map to mouse clicks, no idea how scrolling would be done.... kinda hoping the OS takes care of it. We shall see :)

**Comment by yara-blue** [comment]
Update regarding the OpenGL issue, my [fork](https://github.com/dskleingeld/glow_glyph) of iced_glyph can now display a single letter*! yay... making it fully functional should be easy enough now. 

- [ ] Then I need to change some things about the way the data is presented to the GPU to save on gpu memory to prevent this new old opengl work from being horribly inefficient. 
- [ ] Then port the iced shaders 
- [ ] And finally put it all behind a feature flag and pull request

\* though I cant see it on the pinephone as the window is larger then the screen.... Ill assume all is well and check back once we can write the screen full of text again.

**Comment by black-puppydog** [comment]
> I might be missing a link in there?

I should really get more sleep some day 🙈 
If you have a usb-c dock, you can try and hook it up to a screen to see? That's how I usually work around the window size issues.

**Comment by yara-blue** [comment]
I now have a [fork](https://github.com/dskleingeld/iced) of iced that works on the pinephone (you will need the feature _glow_OpenGL2ES_ enabled when using that fork for something else).

Switching to that allows the app to run on the PinePhone :tada:

**Comment by yara-blue** [comment]
Relevent: https://github.com/hecrj/iced/issues/931
