### ISSUE TITLE
Trying to build on my Pinephone + Mobian

### ISSUE THREAD

**Issue by sehHeiden** [dskleingeld/pods#42]
Hi,

 I just tried to build the main branch on my Pinephone with Mobian. I followed your steps but it failed, because the linker  CC was missing. Seams like gcc is needed (why) and is not installed per default on Mobian(?) Therefore I installed gcc and as I found out that It was  not enough additionalled added the build-essential 's.

Later I got an additional error because cmake was missking. 

So to make thinks easier for compilling on the PinePhone itself please add:

- gcc and build-essential
- cmake

to the Install Dependencies list!

With this I eached building step 387, a bit further even because building continues after failing?

The first problem I see is: checking for vprintf... cflags: -fPIC
...
conftest.c:53:1: note: vprintf: conflicting types for build-in function 'vprintf';
expected 'int(const char *, __va_list)'

so I think, there is still something I missed?

**Comment by sehHeiden** [comment]
I was  able to install after I compiled another podcast app for that I needed:

- libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libhandy-0.0-dev
- libssl-dev

So I guess you also need some of those!

**Comment by yara-blue** [comment]
Hey,

Thanks a lot for bringing this up! I haven't been able to work on this recently and would not have noticed without you. I spun up a fresh virtual Ubuntu and fixed the list of needed packages.
